export const SEARCH_CHANNELS = "SEARCH_CHANNELS";
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_CHANNEL_INFO = "SET_CHANNEL_INFO";
export const SET_CURRENT_CHANNEL_ID = "SET_CURRENT_CHANNEL_ID";
export const SET_CURRENT_CHANNEL_FOLLOWING = "SET_CURRENT_CHANNEL_FOLLOWING";
export const SET_CHANNEL_FOLLOWERS_COUNT = "SET_CHANNEL_FOLLOWERS_COUNT";
